# Generated by Django 3.1.7 on 2021-05-02 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20210501_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('descritpion', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.FileField(upload_to='product')),
                ('is_available', models.BooleanField(default=True)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_modified', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
