# Generated by Django 3.1.7 on 2021-05-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_choices',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('condition', 'condition')], max_length=100),
        ),
    ]
