# Generated by Django 3.1.7 on 2021-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210518_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
